[tool.poetry]
name = "git-profile"
version = "1.0.0"
description = "Python package that helps you easily manage and switch between multiple git profiles."
authors = ["Adrian Pop <popadrian1996@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
