version: 1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8

    steps:
      - checkout
      - run: pip install --user --upgrade pip
      - run: pip install poetry
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - run:
          name: Run Pytest, report coverage
          command: |
            poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs" -m pytest
            poetry run coveralls