version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install poetry
      - run: poetry install
      - run:
          name: run tests
          command: pytest --junitxml=test-reports/junit.xml --cov-report term --cov-report xml --cov=src tests/
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
